<a href="https://colab.research.google.com/github/jfuerst10/data/blob/main/Copy_of_BigQuery_bquxjob_1db4685_189e1b6ad78.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# @title Setup
from google.colab import auth
from google.cloud import bigquery
from google.colab import data_table

project = 'liquid-prod-341719' # Project ID inserted based on the query results selected to explore
location = 'US' # Location inserted based on the query results selected to explore
client = bigquery.Client(project=project, location=location)
data_table.enable_dataframe_formatter()
auth.authenticate_user()

## Reference SQL syntax from the original job
Use the ```jobs.query```
[method](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/query) to
return the SQL syntax from the job. This can be copied from the output cell
below to edit the query now or in the future. Alternatively, you can use
[this link](https://console.cloud.google.com/bigquery?j=liquid-prod-341719:US:bquxjob_1db4685_189e1b6ad78)
back to BigQuery to edit the query within the BigQuery user interface.

In [ ]:
# Running this code will display the query used to generate your previous job

job = client.get_job('bquxjob_1db4685_189e1b6ad78') # Job ID inserted based on the query results selected to explore
print(job.query)

# Result set loaded from BigQuery job as a DataFrame
Query results are referenced from the Job ID ran from BigQuery and the query
does not need to be re-run to explore results. The ```to_dataframe```
[method](https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.job.QueryJob.html#google.cloud.bigquery.job.QueryJob.to_dataframe)
downloads the results to a Pandas DataFrame by using the BigQuery Storage API.

To edit query syntax, you can do so from the BigQuery SQL editor or in the
```Optional:``` sections below.

In [ ]:
# Running this code will read results from your previous job

job = client.get_job('bquxjob_1db4685_189e1b6ad78') # Job ID inserted based on the query results selected to explore
results = job.to_dataframe()
results

Warning: Total number of columns (43) exceeds max_columns (20). Falling back to pandas display.

,topic,trigger,shop_id,id,state,created_at,edited_at,total,order_id,order_name,...,line_items,exchanges,shipment_id,carrier,tracking_number,label_status,label_updated_at,destination_id,return_method,package_reference
0,return,label.updated,1236,36722729,open,2023-08-02T16:38:45+00:00,,58.70,62801184,PC379498,...,"[{'line_item_id': '157295228', 'provider_line_...",[],shp_0a287f8303f94afaa641ac83029369db,USPS,9434636105440161874736,in_transit,2023-08-10T21:53:01+00:00,15864,"{'provider': '', 'return_method_type': '', 'ad...",9434636105440161874736
1,return,label.updated,1236,37056298,open,2023-08-10T01:28:32+00:00,,97.33,63158902,PC379463,...,"[{'line_item_id': '158267385', 'provider_line_...",[],shp_a58e20eb774842b583fd93052ab7c4be,USPS,9434636105440198342673,pre_transit,2023-08-10T21:53:42+00:00,15864,"{'provider': '', 'return_method_type': '', 'ad...",9434636105440198342673
2,return,label.updated,1236,36759369,open,2023-08-03T11:37:07+00:00,,144.93,62840281,PC390075,...,"[{'line_item_id': '157401869', 'provider_line_...",[],shp_42fc25944c6246289b62122b80c1a8ba,USPS,9434636105440165441989,in_transit,2023-08-10T21:54:41+00:00,15864,"{'provider': '', 'return_method_type': '', 'ad...",9434636105440165441989
3,return,label.updated,1236,36884006,open,2023-08-06T14:35:25+00:00,,144.36,62974545,PC388200,...,"[{'line_item_id': '157766396', 'provider_line_...",[],shp_4ff91f0b39664f5c9bac0bf0212ba6d2,USPS,9434636105440177696797,in_transit,2023-08-10T21:57:10+00:00,15864,"{'provider': '', 'return_method_type': '', 'ad...",9434636105440177696797
4,return,label.updated,1236,37058654,open,2023-08-10T02:36:05+00:00,,75.08,63161510,PC401389,...,"[{'line_item_id': '158274502', 'provider_line_...",[],shp_9b7bd75b1b4b4edf8a64f1dce75c06f6,USPS,9434636105440198439144,pre_transit,2023-08-10T21:59:15+00:00,15864,"{'provider': '', 'return_method_type': '', 'ad...",9434636105440198439144
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9766,return,return.closed,1236,36703666,closed,2023-08-02T03:26:00+00:00,,-204.90,62780236,PC386205,...,"[{'line_item_id': '157238534', 'provider_line_...","[{'exchange_id': '16666700', 'product_id': '75...",shp_0358deaa930e4129971d5d2629aa7ceb,USPS,9434636105440159173162,in_transit,2023-08-03T23:46:46+00:00,15864,"{'provider': '', 'return_method_type': '', 'ad...",9434636105440159173162
9767,return,return.updated,1236,36169870,cancelled,2023-07-20T21:37:57+00:00,,2041.75,62206333,PC362509,...,[],[],N/A,N/A,N/A,N/A,N/A,0,"{'provider': '', 'return_method_type': '', 'ad...",
9768,return,return.closed,1236,36427288,closed,2023-07-26T20:09:07+00:00,,2392.49,61175292,PC372504,...,"[{'line_item_id': '152810976', 'provider_line_...",[],N/A,N/A,N/A,N/A,N/A,0,"{'provider': '', 'return_method_type': '', 'ad...",
9769,return,return.updated,1236,36643893,cancelled,2023-07-31T23:31:20+00:00,,2419.89,62715863,PC368570,...,"[{'line_item_id': '157062988', 'provider_line_...",[],N/A,N/A,N/A,N/A,N/A,0,"{'provider': '', 'return_method_type': '', 'ad...",
9770,return,return.updated,1236,36000382,cancelled,2023-07-17T17:27:57+00:00,,2745.36,62024633,PC371006,...,"[{'line_item_id': '155168849', 'provider_line_...",[],N/A,N/A,N/A,N/A,N/A,0,"{'provider': '', 'return_method_type': '', 'ad...",

## Show descriptive statistics using describe()
Use the ```pandas DataFrame.describe()```
[method](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html)
to generate descriptive statistics. Descriptive statistics include those that
summarize the central tendency, dispersion and shape of a dataset’s
distribution, excluding ```NaN``` values. You may also use other Python methods
to interact with your data.

In [ ]:
results.describe()